export const ADD_PLAN_EVENT_REQUEST = 'App/ADD_PLAN_EVENT_REQUEST';
export const ADD_PLAN_EVENT_SUCCESS = 'App/ADD_PLAN_EVENT_SUCCESS';
export const ADD_PLAN_EVENT_FAILURE = 'App/ADD_PLAN_EVENT_FAILURE';
export const GET_PLAN_EVENT_REQUEST = 'App/GET_PLAN_EVENT_REQUEST';
export const GET_PLAN_EVENT_SUCCESS = 'App/GET_PLAN_EVENT_SUCCESS';
export const GET_PLAN_EVENT_FAILURE = 'App/GET_PLAN_EVENT_FAILURE';
export const GET_PLAN_EVENTS_REQUEST = 'App/GET_PLAN_EVENTS_REQUEST';
export const GET_PLAN_EVENTS_BY_CLIENT_ID_REQUEST =
  'App/GET_PLAN_EVENTS_BY_CLIENT_ID_REQUEST';
export const GET_PLAN_EVENTS_SUCCESS = 'App/GET_PLAN_EVENTS_SUCCESS';
export const GET_PLAN_EVENTS_FAILURE = 'App/GET_PLAN_EVENTS_FAILURE';
export const UPDATE_PLAN_EVENT_REQUEST = 'App/UPDATE_PLAN_EVENT_REQUEST';
export const UPDATE_PLAN_EVENT_SUCCESS = 'App/UPDATE_PLAN_EVENT_SUCCESS';
export const UPDATE_PLAN_EVENT_FAILURE = 'App/UPDATE_PLAN_EVENT_FAILURE';
export const DELETE_PLAN_EVENT_REQUEST = 'App/DELETE_PLAN_EVENT_REQUEST';
export const DELETE_PLAN_EVENT_FAILURE = 'App/DELETE_PLAN_EVENT_FAILURE';
export const DELETE_PLAN_EVENT_SUCCESS = 'App/DELETE_PLAN_EVENT_SUCCESS';
