export const ADD_PLAN_REQUEST = 'App/ADD_PLAN_REQUEST';
export const ADD_PLAN_SUCCESS = 'App/ADD_PLAN_SUCCESS';
export const ADD_PLAN_FAILURE = 'App/ADD_PLAN_FAILURE';
export const GET_PLAN_REQUEST = 'App/GET_PLAN_REQUEST';
export const GET_PLAN_SUCCESS = 'App/GET_PLAN_SUCCESS';
export const GET_PLAN_FAILURE = 'App/GET_PLAN_FAILURE';
export const GET_PLANS_REQUEST = 'App/GET_PLANS_REQUEST';
export const GET_PLANS_BY_CLIENT_ID_REQUEST =
  'App/GET_PLANS_BY_CLIENT_ID_REQUEST';
export const GET_ACTIVE_PLANS_BY_CLIENT_ID_REQUEST =
  'App/GET_ACTIVE_PLANS_BY_CLIENT_ID_REQUEST';
export const GET_PLANS_SUCCESS = 'App/GET_PLANS_SUCCESS';
export const GET_PLANS_FAILURE = 'App/GET_PLANS_FAILURE';
export const UPDATE_PLAN_REQUEST = 'App/UPDATE_PLAN_REQUEST';
export const UPDATE_PLAN_SUCCESS = 'App/UPDATE_PLAN_SUCCESS';
export const UPDATE_PLAN_FAILURE = 'App/UPDATE_PLAN_FAILURE';
